spring.datasource.url=jdbc:mysql://localhost:3306/userregistration
spring.datasource.url=jdbc:mysql://localhost:3306/accountstmgeneration
spring.datasource.url=jdbc:mysql://localhost:3306/balanceinquiry
spring.datasource.url=jdbc:mysql://localhost:3306/billpayment
spring.datasource.url=jdbc:mysql://localhost:3306/fundtransfer
spring.datasource.url=jdbc:mysql://localhost:3306/loan_application
spring.datasource.url=jdbc:mysql://localhost:3306/transactionhistoryreview
spring.datasource.url=jdbc:mysql://localhost:3306/updatepersonalinfo
spring.datasource.username=root
spring.datasource.password=prasad123

debug=true

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
eureka.client.service-url.defaultZone=http://localhost:8096/eureka/
spring.cloud.loadbalancer.retry.enabled=true

